site_name: DUCB230V

nav:
  - Introduzione: index.md
  - Dati Tecnici: wiring.md
  - Fotocellule: photocells.md
  - Antenna: antenna.md
  - Menu:
    - Menu principale: main_menu.md
    - Menu base: menu_base.md
    - Menu avanzato: menu_avanzato.md
    - Menu impianto: menu_impianto.md
    - Menu impostazioni: menu_impostazioni.md
    - Menu info: menu_info.md
  - Installazione:
    - Battente 2 ante <br>(Elettro-meccanico): installazione_battente_2_ante_elettromeccanico.md
    - Battente 1 anta <br>(Elettro-meccanico): installazione_battente_1_anta_elettromeccanico.md
    - Battente 2 ante <br>(Oleodinamico): installazione_battente_2_ante_oleodinamico.md
    - Battente 1 anta <br>(Oleodinamico) : installazione_battente_1_anta_oleodinamico
  - Logica di funzionamento: logica.md
  - Segnalazione:
    - Segnalazione spia cancello aperto: segnalazione_sca.md
    - Segnalazione lampeggiante : segnalazione_lamp.md
    - Segnalazione errori display : segnalazione_allarmi.md
  - Telecomandi: telecomandi.md

plugins:
  - search:
      lang: it
      separator: '[\s\-\.]'

theme:
  name: material
  highlightjs: true
  language: it
  features:
    - search.suggest
    - navigation.tracking
    - search.highlight
    - header.autohide
    - announce.dismiss
    - content.tabs.link
  palette:
    primary: red

markdown_extensions:
  - attr_list
  - md_in_html
  - markdown.extensions.extra
  - admonition
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.